# Site settings
header: "sreejithgp"
title: "sreejithgp"
bye_message: "Thx!"
baseurl: "/"
url: "https://sreejithgp.github.io/"
disqus: SreejithGPillai

# Header settings
nick: "sreejithgp"
mail:
    domain: "sreejith.gp"
    ext: "icloud"
source_code:
    server: "github.com"
    nick: "sreejithgp"
blog:
    server: "wordpress.com"
    nick: "gjuniioor"
fingerprint_key: "5E12 9ABC C2A9 564B C048  2DF9 D327 0D10 BC71 CF75"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
